site_name: AI Security Certification & Training
site_description: Comprehensive AI Security education and professional certification training
site_author: AI Security Pro Team
site_url: https://varunsxo.github.io/ai-security-certification-and-training/

repo_name: varunsxo/ai-security-certification-and-training
repo_url: https://github.com/varunsxo/ai-security-certification-and-training
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Inter
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.delay
    - navigation.instant.loading
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/varunsxo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aisecuritypro
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/aisecuritypro

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()/]+'
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
  - Courses:
    - Certified AI Security Professional: courses/certified-ai-security-professional.md
    - Advanced AI Security: courses/advanced-ai-security.md
    - Team Training: courses/team-training.md
  - Blog:
    - Best AI Security Certification: blog/best-ai-security-certification.md
    - AI Security Fundamentals: blog/ai-security-fundamentals.md
    - Career Guide: blog/career-guide.md
  - Reference:
    - Course Syllabus: reference/syllabus.md
    - Certification Requirements: reference/certification-requirements.md
    - FAQ: reference/faq.md
  - About:
    - About Us: about/about-us.md
    - Contact: about/contact.md 